IF
Global("SanTotStart","Global",1)
GlobalGT("ToGodwalk","Global",5)
Global("ToTablet1","Global",0)
THEN
RESPONSE #100
SetGlobal("ToTablet1","Global",1)
CreateCreature("Tosune",[1343.1489],4)
CreateCreature("Tomyst",[1487.1459],6)
END

IF
Global("ToTablet1","Global",10)
PartyHasItem("Totabl1")
Global("MoveMyst","RTF005",0)
THEN
RESPONSE #100
SetGlobal("MoveMyst","RTF005",1)
ActionOverride("Tomyst",MoveBetweenAreas("Tot005",[2033.1900],12)
END
