IF
GlobalGT("ToTablet1","Global",11)
THEN
RESPONSE #100
ClearAllActions()
ActionOverride(Player1,LeaveAreaLUA("TOT004","",[382.906],9))
ActionOverride(Player2,LeaveAreaLUA("TOT004","",[382.906],10))
ActionOverride(Player3,LeaveAreaLUA("TOT004","",[382.906],9))
ActionOverride(Player4,LeaveAreaLUA("TOT004","",[382.906],7))
ActionOverride(Player5,LeaveAreaLUA("TOT004","",[382.906],11))
ActionOverride(Player6,LeaveAreaLUA("TOT004","",[382.906],9))
END