IF
Global("ToBaneHunt","Global",9)
Global("Sailors","RTF381",0)
THEN
RESPONSE #100
SetGlobal("Sailors","RTF381",1)
CreateCreature("Acqxzah1",[580.480],6)
CreateCreature("sailfin",[650.500],11)
CreateCreature("sailjos",[600.600],4)
END

IF
Global("Sailors","RTF381",4)
InMyArea("Acqxzah1")
THEN
RESPONSE #100
ActionOverride("Acqxzah1",DestroySelf())
END   

IF
Global("Sailors","RTF381",4)
InMyArea("Tonarth")
THEN
RESPONSE #100
ActionOverride("Tonarth",DestroySelf())
END
