IF
Global("SanTotStart","Global",1)
HasItem("Ghost",Myself)
THEN
RESPONSE #100
DestroyItem("ghost")
END

IF
AreaCheck("Tot010")
Dead("ToMoand")
!StateCheck(Myself,CD_STATE_NOTVALID)
!StateCheck("CVsandr",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("ToBaneHunt","Global",10)
StartDialogueNoSet("ToFind")
END

IF
AreaCheck("CVDre1")
See("CVSandr")
Global("TotPeople","CVDre1",2)
THEN
RESPONSE #100
StartDialogueNoSet("ToElmi")
END
