IF
Die()
THEN
RESPONSE #100
Kill(Player1)
END

IF 
AreaCheck("BG4100")
Global("Tolini","BG4100",7)
Delay(12)
THEN
RESPONSE #100
SetGlobal("Tolini","BG4100",8)
END

IF
Global("Tolini","BG4100",8)
InParty(Myself)
!See([ENEMY])
See(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID)
CombatCounter(0)
!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogNoSet(Player1)
END

